<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/29_Keras_Tuner_Hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/DeepLearning/master/diabetes_1.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()["Outcome"]  #to check which coloumn is useful ,we can ignore unused column

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [6]:
scale=StandardScaler()
X=scale.fit_transform(X)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=1)

In [8]:
model=Sequential()
model.add(Dense(32,activation="relu", input_dim=8))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer="adam",loss="binary_crossentropy", metrics=["accuracy"])

In [11]:
model.fit(X_train,y_train,batch_size=32,epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - accuracy: 0.6384 - loss: 0.6680 - val_accuracy: 0.6688 - val_loss: 0.6729
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6971 - loss: 0.6256 - val_accuracy: 0.7338 - val_loss: 0.6327
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7117 - loss: 0.5947 - val_accuracy: 0.7792 - val_loss: 0.6008
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7231 - loss: 0.5685 - val_accuracy: 0.7987 - val_loss: 0.5753
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7296 - loss: 0.5471 - val_accuracy: 0.7987 - val_loss: 0.5589
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7443 - loss: 0.5300 - val_accuracy: 0.7922 - val_loss: 0.5433
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5162 - val_accuracy: 0.7857 - val_loss: 0.5314
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.5056 - val_accuracy: 0.7922 - val_loss: 0.5218
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.4969 - val_accuracy: 0.7922 - val_loss: 0.5136
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.4903 - val_accuracy: 0.8052 - val_loss: 0.5068
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4843 - val_accuracy: 0.7987 - val_loss: 0.5021
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4795 - val_accuracy: 0.7922 - val_loss: 0.4980
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4753 - val_accuracy: 0.7922 - val_loss: 0.4943
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7638 - loss: 0.4719 - val_accuracy: 0.7922 - val_loss: 0.4923
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7720 - loss: 0.4684 - val_accuracy: 0.7987 - val_loss: 0.4901
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7704 - loss: 0.4657 - val_accuracy: 0.7922 - val_loss: 0.4883
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7720 - loss: 0.4632 - val_accuracy: 0.7922 - val_loss: 0.4871
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4616 - val_accuracy: 0.7857 - val_loss: 0.4860
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4593 - val_accuracy: 0.7857 - val_loss: 0.4845
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4582 - val_accuracy: 0.7857 - val_loss: 0.4842
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4557 - val_accuracy: 0.7857 - val_loss: 0.4833
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4544 - val_accuracy: 0.7792 - val_loss: 0.4833
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4535 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4520 - val_accuracy: 0.7987 - val_loss: 0.4822
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4509 - val_accuracy: 0.7922 - val_loss: 0.4831
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4496 - val_accuracy: 0.7922 - val_loss: 0.4830
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4488 - val_accuracy: 0.7922 - val_loss: 0.4821
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4485 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4475 - val_accuracy: 0.7922 - val_loss: 0.4833
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4458 - val_accuracy: 0.7922 - val_loss: 0.4820
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4454 - val_accuracy: 0.7987 - val_loss: 0.4808
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4811
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4437 - val_accuracy: 0.8052 - val_loss: 0.4794
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4426 - val_accuracy: 0.7987 - val_loss: 0.4795
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4417 - val_accuracy: 0.7987 - val_loss: 0.4802
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4415 - val_accuracy: 0.8182 - val_loss: 0.4801
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4410 - val_accuracy: 0.7987 - val_loss: 0.4789
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4406 - val_accuracy: 0.8052 - val_loss: 0.4800
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4401 - val_accuracy: 0.7987 - val_loss: 0.4797
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4386 - val_accuracy: 0.8117 - val_loss: 0.4780
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4382 - val_accuracy: 0.8052 - val_loss: 0.4784
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4373 - val_accuracy: 0.8117 - val_loss: 0.4768
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4365 - val_accuracy: 0.8052 - val_loss: 0.4774
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4365 - val_accuracy: 0.8052 - val_loss: 0.4774
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4352 - val_accuracy: 0.8117 - val_loss: 0.4765
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4352 - val_accuracy: 0.8117 - val_loss: 0.4776
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4347 - val_accuracy: 0.8117 - val_loss: 0.4766
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4340 - val_accuracy: 0.8182 - val_loss: 0.4764
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4338 - val_accuracy: 0.8117 - val_loss: 0.4761
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4334 - val_accuracy: 0.8052 - val_loss: 0.4773
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4328 - val_accuracy: 0.8052 - val_loss: 0.4756
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4320 - val_accuracy: 0.8052 - val_loss: 0.4769
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4320 - val_accuracy: 0.8117 - val_loss: 0.4763
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4311 - val_accuracy: 0.8182 - val_loss: 0.4754
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4743
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4300 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4297 - val_accuracy: 0.8117 - val_loss: 0.4748
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4294 - val_accuracy: 0.8182 - val_loss: 0.4752
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4285 - val_accuracy: 0.8182 - val_loss: 0.4734
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4289 - val_accuracy: 0.8182 - val_loss: 0.4743
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4283 - val_accuracy: 0.8182 - val_loss: 0.4740
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4281 - val_accuracy: 0.8182 - val_loss: 0.4738
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4271 - val_accuracy: 0.8182 - val_loss: 0.4740
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4270 - val_accuracy: 0.8182 - val_loss: 0.4739
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4270 - val_accuracy: 0.8117 - val_loss: 0.4740
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4265 - val_accuracy: 0.8182 - val_loss: 0.4725
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4260 - val_accuracy: 0.8182 - val_loss: 0.4721
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4265 - val_accuracy: 0.8182 - val_loss: 0.4716
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4255 - val_accuracy: 0.8182 - val_loss: 0.4731
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4739
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4247 - val_accuracy: 0.8182 - val_loss: 0.4732
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4244 - val_accuracy: 0.8182 - val_loss: 0.4728
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4242 - val_accuracy: 0.8182 - val_loss: 0.4728
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4235 - val_accuracy: 0.8182 - val_loss: 0.4727
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4237 - val_accuracy: 0.8182 - val_loss: 0.4720
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4239 - val_accuracy: 0.8117 - val_loss: 0.4734
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4727
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4227 - val_accuracy: 0.8117 - val_loss: 0.4713
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4229 - val_accuracy: 0.8117 - val_loss: 0.4721
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4217 - val_accuracy: 0.8117 - val_loss: 0.4718
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4214 - val_accuracy: 0.8052 - val_loss: 0.4720
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4214 - val_accuracy: 0.8117 - val_loss: 0.4705
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4217 - val_accuracy: 0.7987 - val_loss: 0.4721
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4207 - val_accuracy: 0.8052 - val_loss: 0.4718
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4207 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4200 - val_accuracy: 0.8052 - val_loss: 0.4697
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4197 - val_accuracy: 0.8117 - val_loss: 0.4696
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4194 - val_accuracy: 0.8117 - val_loss: 0.4698
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4199 - val_accuracy: 0.8117 - val_loss: 0.4696
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4189 - val_accuracy: 0.8117 - val_loss: 0.4697
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4186 - val_accuracy: 0.8052 - val_loss: 0.4693
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4687
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.8052 - val_loss: 0.4692
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4177 - val_accuracy: 0.8052 - val_loss: 0.4690
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4173 - val_accuracy: 0.8117 - val_loss: 0.4696
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4175 - val_accuracy: 0.7987 - val_loss: 0.4695
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4167 - val_accuracy: 0.8182 - val_loss: 0.4698
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4163 - val_accuracy: 0.8117 - val_loss: 0.4698
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4167 - val_accuracy: 0.8052 - val_loss: 0.4708

In [12]:
#.How to select Appropriate Optimizer
#No of Nodes In a layers
# how to select no of Hidden layers
#All in one

**#.How to select Appropriate Optimizer**

In [17]:
#pip install -U keras.tuner

In [18]:
import keras_tuner as kt

In [19]:
def build_model(hp):

  model=Sequential()
  model.add(Dense(32,activation="relu", input_dim=8))
  model.add(Dense(1,activation="sigmoid"))

  optimizer=hp.Choice("optimizer", values=["adam","sgd","rmsprop","Adagrad"])

  model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
  return model

In [20]:
tuner = kt.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=5
)

In [21]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 08s

In [22]:
tuner.search_space_summary()

Search space summary
Default search space size: 1
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'sgd', 'rmsprop', 'Adagrad'], 'ordered': False}

In [23]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.8181818127632141

Trial 3 summary
Hyperparameters:
optimizer: adam
Score: 0.7792207598686218

Trial 0 summary
Hyperparameters:
optimizer: sgd
Score: 0.6688311696052551

Trial 1 summary
Hyperparameters:
optimizer: Adagrad
Score: 0.3311688303947449

In [24]:
best_hps = tuner.get_best_hyperparameters()[0].values

In [25]:
best_hps

{'optimizer': 'rmsprop'}

In [26]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7573 - loss: 0.4977 - val_accuracy: 0.8117 - val_loss: 0.4844
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4860 - val_accuracy: 0.8052 - val_loss: 0.4787
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4794 - val_accuracy: 0.7857 - val_loss: 0.4748
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4744 - val_accuracy: 0.7792 - val_loss: 0.4728
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4702 - val_accuracy: 0.7792 - val_loss: 0.4713
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4677 - val_accuracy: 0.7792 - val_loss: 0.4696
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4645 - val_accuracy: 0.7857 - val_loss: 0.4682
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4625 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4601 - val_accuracy: 0.7922 - val_loss: 0.4662
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4587 - val_accuracy: 0.7987 - val_loss: 0.4647
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4572 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4555 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4546 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4538 - val_accuracy: 0.7922 - val_loss: 0.4624
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4526 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4515 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4511 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4502 - val_accuracy: 0.7857 - val_loss: 0.4642
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4494 - val_accuracy: 0.7857 - val_loss: 0.4639
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4486 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4481 - val_accuracy: 0.7857 - val_loss: 0.4628
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4474 - val_accuracy: 0.7857 - val_loss: 0.4629
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4470 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4460 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4458 - val_accuracy: 0.7792 - val_loss: 0.4624
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4449 - val_accuracy: 0.7792 - val_loss: 0.4634
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4445 - val_accuracy: 0.7792 - val_loss: 0.4628
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4433 - val_accuracy: 0.7792 - val_loss: 0.4628
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4425 - val_accuracy: 0.7857 - val_loss: 0.4626
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4423 - val_accuracy: 0.7857 - val_loss: 0.4625
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4420 - val_accuracy: 0.7857 - val_loss: 0.4628
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4410 - val_accuracy: 0.7857 - val_loss: 0.4628
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4406 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4398 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4395 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4390 - val_accuracy: 0.7922 - val_loss: 0.4617
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4383 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4382 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4369 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4366 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4358 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4352 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4350 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4341 - val_accuracy: 0.8182 - val_loss: 0.4595
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4612
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4332 - val_accuracy: 0.8117 - val_loss: 0.4609
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4328 - val_accuracy: 0.8117 - val_loss: 0.4614
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4323 - val_accuracy: 0.8182 - val_loss: 0.4619
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4319 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4316 - val_accuracy: 0.8117 - val_loss: 0.4623
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4310 - val_accuracy: 0.8052 - val_loss: 0.4626
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4305 - val_accuracy: 0.7987 - val_loss: 0.4627
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4301 - val_accuracy: 0.8052 - val_loss: 0.4621
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4295 - val_accuracy: 0.8117 - val_loss: 0.4619
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4294 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4287 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4288 - val_accuracy: 0.8182 - val_loss: 0.4616
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4276 - val_accuracy: 0.8182 - val_loss: 0.4613
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4276 - val_accuracy: 0.8182 - val_loss: 0.4613
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4277 - val_accuracy: 0.8182 - val_loss: 0.4614
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4269 - val_accuracy: 0.8182 - val_loss: 0.4615
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4264 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4257 - val_accuracy: 0.8247 - val_loss: 0.4619
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4255 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4245 - val_accuracy: 0.8182 - val_loss: 0.4628
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4630
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4244 - val_accuracy: 0.8247 - val_loss: 0.4625
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4235 - val_accuracy: 0.8247 - val_loss: 0.4628
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4233 - val_accuracy: 0.8247 - val_loss: 0.4634
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4233 - val_accuracy: 0.8247 - val_loss: 0.4641
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4229 - val_accuracy: 0.8182 - val_loss: 0.4631
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4226 - val_accuracy: 0.8247 - val_loss: 0.4630
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4226 - val_accuracy: 0.8247 - val_loss: 0.4627
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4222 - val_accuracy: 0.8377 - val_loss: 0.4618
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4219 - val_accuracy: 0.8182 - val_loss: 0.4618
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4217 - val_accuracy: 0.8312 - val_loss: 0.4610
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4211 - val_accuracy: 0.8312 - val_loss: 0.4615
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4210 - val_accuracy: 0.8312 - val_loss: 0.4601
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4596
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4203 - val_accuracy: 0.8182 - val_loss: 0.4599
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4199 - val_accuracy: 0.8182 - val_loss: 0.4590
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4194 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4194 - val_accuracy: 0.8182 - val_loss: 0.4594
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4187 - val_accuracy: 0.8182 - val_loss: 0.4599
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4190 - val_accuracy: 0.8182 - val_loss: 0.4605
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4180 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4184 - val_accuracy: 0.8052 - val_loss: 0.4616
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4179 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4177 - val_accuracy: 0.8117 - val_loss: 0.4609
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4172 - val_accuracy: 0.8052 - val_loss: 0.4607

In [47]:
def build_model1(hp):
    model = keras.Sequential()

    units=hp.Int("units",min_value=8, max_value=128, step=32)
    model.add(Dense(units=units, activation="relu",input_dim=8))
    model.add(Dense(1,activation="sigmoid"))

    model.compile(optimizer="rmsprop",loss="binary_crossentropy", metrics=["accuracy"])

    return model

In [48]:
tuner1 = kt.RandomSearch(
    hypermodel=build_model1,
    objective="val_accuracy",
    max_trials=5, directory="mydir"
)

In [49]:
tuner1.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 09s

In [51]:
tuner1.search_space_summary()

Search space summary
Default search space size: 1
units (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 32, 'sampling': 'linear'}

In [52]:
tuner1.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
units: 40
Score: 0.8181818127632141

Trial 1 summary
Hyperparameters:
units: 72
Score: 0.7857142686843872

Trial 3 summary
Hyperparameters:
units: 104
Score: 0.7857142686843872

Trial 2 summary
Hyperparameters:
units: 8
Score: 0.7077922224998474

In [53]:
best_hps = tuner1.get_best_hyperparameters()[0].values

In [54]:
best_hps

{'units': 40}

In [56]:
model=tuner1.get_best_models(num_models=1)[0]

In [57]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 40)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401 (1.57 KB)

 Trainable params: 401 (1.57 KB)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - accuracy: 0.7655 - loss: 0.4947 - val_accuracy: 0.8312 - val_loss: 0.4897
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7720 - loss: 0.4820 - val_accuracy: 0.8182 - val_loss: 0.4822
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4748 - val_accuracy: 0.8117 - val_loss: 0.4773
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4692 - val_accuracy: 0.8117 - val_loss: 0.4739
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4651 - val_accuracy: 0.8182 - val_loss: 0.4716
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4623 - val_accuracy: 0.8117 - val_loss: 0.4707
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4593 - val_accuracy: 0.7987 - val_loss: 0.4698
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4569 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4554 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4534 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4523 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4505 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4499 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4490 - val_accuracy: 0.7987 - val_loss: 0.4662
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4476 - val_accuracy: 0.7987 - val_loss: 0.4659
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4465 - val_accuracy: 0.7987 - val_loss: 0.4653
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4460 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4450 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4445 - val_accuracy: 0.7987 - val_loss: 0.4662
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4435 - val_accuracy: 0.7987 - val_loss: 0.4657
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4427 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4420 - val_accuracy: 0.7987 - val_loss: 0.4653
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4640
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4405 - val_accuracy: 0.7857 - val_loss: 0.4626
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4401 - val_accuracy: 0.7857 - val_loss: 0.4631
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4394 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4388 - val_accuracy: 0.7922 - val_loss: 0.4613
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4380 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4374 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4371 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4365 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4356 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4354 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4346 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4613
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4331 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4324 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4318 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4312 - val_accuracy: 0.7792 - val_loss: 0.4586
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4306 - val_accuracy: 0.7857 - val_loss: 0.4579
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4302 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4304 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.8117 - val_loss: 0.4583
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4288 - val_accuracy: 0.8117 - val_loss: 0.4589
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4284 - val_accuracy: 0.8117 - val_loss: 0.4581
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4576
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4273 - val_accuracy: 0.8052 - val_loss: 0.4568
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4266 - val_accuracy: 0.8182 - val_loss: 0.4573
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4573
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4262 - val_accuracy: 0.8182 - val_loss: 0.4556
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4255 - val_accuracy: 0.8182 - val_loss: 0.4546
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4254 - val_accuracy: 0.8117 - val_loss: 0.4544
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4245 - val_accuracy: 0.7987 - val_loss: 0.4548
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4244 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4235 - val_accuracy: 0.8052 - val_loss: 0.4552
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4242 - val_accuracy: 0.8117 - val_loss: 0.4540
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4226 - val_accuracy: 0.8117 - val_loss: 0.4540
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4224 - val_accuracy: 0.8117 - val_loss: 0.4537
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4226 - val_accuracy: 0.8117 - val_loss: 0.4547
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4212 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4209 - val_accuracy: 0.8117 - val_loss: 0.4541
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4207 - val_accuracy: 0.7987 - val_loss: 0.4531
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4202 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4196 - val_accuracy: 0.8052 - val_loss: 0.4539
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4197 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4196 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4190 - val_accuracy: 0.8117 - val_loss: 0.4523
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4186 - val_accuracy: 0.8117 - val_loss: 0.4522
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4180 - val_accuracy: 0.8117 - val_loss: 0.4526
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4180 - val_accuracy: 0.8117 - val_loss: 0.4515
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4172 - val_accuracy: 0.8117 - val_loss: 0.4528
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4173 - val_accuracy: 0.8117 - val_loss: 0.4520
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4169 - val_accuracy: 0.8117 - val_loss: 0.4518
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4168 - val_accuracy: 0.8117 - val_loss: 0.4524
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4169 - val_accuracy: 0.8117 - val_loss: 0.4528
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4161 - val_accuracy: 0.8117 - val_loss: 0.4520
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4160 - val_accuracy: 0.8117 - val_loss: 0.4515
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4157 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4153 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4151 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4145 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4143 - val_accuracy: 0.8182 - val_loss: 0.4544
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4141 - val_accuracy: 0.8117 - val_loss: 0.4541
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4140 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4134 - val_accuracy: 0.8182 - val_loss: 0.4532
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4132 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4129 - val_accuracy: 0.8182 - val_loss: 0.4538
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4128 - val_accuracy: 0.8117 - val_loss: 0.4536
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4118 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4123 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4115 - val_accuracy: 0.8182 - val_loss: 0.4526

In [70]:
def build_model2(hp):

  model=Sequential()
  model.add(Dense(40,activation="relu", input_dim=8))
  for i in range(hp.Int("num_layers", 1, 10)):
    model.add(Dense(40,activation="relu"))

  model.add(Dense(1,activation="sigmoid"))
  model.compile(optimizer="rmsprop",loss="binary_crossentropy", metrics=["accuracy"])

  return model

In [71]:
tuner2 = kt.RandomSearch(
    hypermodel=build_model2,
    objective="val_accuracy",
    max_trials=5,directory="mydir1"
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [72]:
tuner2.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 16s

In [73]:
tuner2.search_space_summary()

Search space summary
Default search space size: 1
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 10, 'step': 1, 'sampling': 'linear'}

In [74]:
tuner2.results_summary()

Results summary
Results in mydir1/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 4 summary
Hyperparameters:
num_layers: 7
Score: 0.8116883039474487

Trial 1 summary
Hyperparameters:
num_layers: 2
Score: 0.8051947951316833

Trial 3 summary
Hyperparameters:
num_layers: 10
Score: 0.798701286315918

Trial 2 summary
Hyperparameters:
num_layers: 5
Score: 0.7922077775001526

Trial 0 summary
Hyperparameters:
num_layers: 4
Score: 0.7792207598686218

In [76]:
best_hps = tuner2.get_best_hyperparameters()[0].values

In [77]:
best_hps

{'num_layers': 7}

In [80]:
model=tuner2.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 20 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [81]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 40)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,881 (46.41 KB)

 Trainable params: 11,881 (46.41 KB)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0055 - val_accuracy: 0.6948 - val_loss: 2.0777
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0115 - val_accuracy: 0.7013 - val_loss: 2.6491
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9642 - loss: 0.0916 - val_accuracy: 0.6948 - val_loss: 2.0969
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.6818 - val_loss: 2.1609
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.7013 - val_loss: 2.2966
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9853 - loss: 0.0638 - val_accuracy: 0.7078 - val_loss: 2.1885
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9870 - loss: 0.0383 - val_accuracy: 0.6948 - val_loss: 2.0078
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9886 - loss: 0.0336 - val_accuracy: 0.7013 - val_loss: 2.1915
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9951 - loss: 0.0142 - val_accuracy: 0.7143 - val_loss: 2.0794
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.7143 - val_loss: 2.5579
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9691 - loss: 0.0671 - val_accuracy: 0.7143 - val_loss: 2.2120
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0096 - val_accuracy: 0.7143 - val_loss: 2.1414
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.7078 - val_loss: 2.2086
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9902 - loss: 0.0496 - val_accuracy: 0.7013 - val_loss: 2.2267
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9853 - loss: 0.0370 - val_accuracy: 0.7208 - val_loss: 2.4136
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9967 - loss: 0.0121 - val_accuracy: 0.7143 - val_loss: 2.2476
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.7143 - val_loss: 2.3694
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9870 - loss: 0.0425 - val_accuracy: 0.7338 - val_loss: 2.3944
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9935 - loss: 0.0307 - val_accuracy: 0.6948 - val_loss: 2.2822
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9967 - loss: 0.0208 - val_accuracy: 0.7143 - val_loss: 2.0806
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9935 - loss: 0.0316 - val_accuracy: 0.7078 - val_loss: 2.1466
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9951 - loss: 0.0147 - val_accuracy: 0.7208 - val_loss: 2.2179
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9870 - loss: 0.0508 - val_accuracy: 0.6753 - val_loss: 2.2291
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9919 - loss: 0.0370 - val_accuracy: 0.7143 - val_loss: 2.1451
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.9935 - loss: 0.0115 - val_accuracy: 0.7208 - val_loss: 2.2176
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9984 - loss: 0.0048 - val_accuracy: 0.7208 - val_loss: 2.2676
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 1.0000 - loss: 9.9476e-04 - val_accuracy: 0.7078 - val_loss: 2.4064
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.9788 - loss: 0.0657 - val_accuracy: 0.6753 - val_loss: 2.4802
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9902 - loss: 0.0404 - val_accuracy: 0.7273 - val_loss: 2.5118
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9967 - loss: 0.0065 - val_accuracy: 0.7208 - val_loss: 2.3942
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 7.6084e-04 - val_accuracy: 0.7078 - val_loss: 2.5374
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.1194 - val_accuracy: 0.7208 - val_loss: 2.5912
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0125 - val_accuracy: 0.7273 - val_loss: 2.8492
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0232 - val_accuracy: 0.7013 - val_loss: 2.4851
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.1404e-04 - val_accuracy: 0.7013 - val_loss: 2.5454
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.9580e-04 - val_accuracy: 0.7013 - val_loss: 2.6326
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.9768e-04 - val_accuracy: 0.7078 - val_loss: 2.7601
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0573 - val_accuracy: 0.7078 - val_loss: 2.4947
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0145 - val_accuracy: 0.7078 - val_loss: 2.6072
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9967 - loss: 0.0074 - val_accuracy: 0.7208 - val_loss: 2.4765
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.1637e-04 - val_accuracy: 0.7143 - val_loss: 2.5658
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.0915e-04 - val_accuracy: 0.7143 - val_loss: 2.7094
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0758 - val_accuracy: 0.7013 - val_loss: 2.6571
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.7078 - val_loss: 2.5706
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7208 - val_loss: 2.6823
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.5301e-04 - val_accuracy: 0.7013 - val_loss: 2.9152
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.7195e-04 - val_accuracy: 0.6948 - val_loss: 2.9343
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0055 - val_accuracy: 0.7532 - val_loss: 2.9737
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0753 - val_accuracy: 0.7013 - val_loss: 2.8610
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0052 - val_accuracy: 0.7013 - val_loss: 2.9693
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9902 - loss: 0.0377 - val_accuracy: 0.7273 - val_loss: 2.8577
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.7208 - val_loss: 2.9411
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.9293e-04 - val_accuracy: 0.7143 - val_loss: 2.9974
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3684e-04 - val_accuracy: 0.7143 - val_loss: 3.0586
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.0614e-05 - val_accuracy: 0.7143 - val_loss: 3.1838
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.7401e-05 - val_accuracy: 0.7078 - val_loss: 3.3757
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0538 - val_accuracy: 0.7273 - val_loss: 3.0003
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0124 - val_accuracy: 0.7273 - val_loss: 3.3861
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9756 - loss: 0.0955 - val_accuracy: 0.7273 - val_loss: 2.5190
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0147 - val_accuracy: 0.7078 - val_loss: 2.6201
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.7338 - val_loss: 2.7696
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0324 - val_accuracy: 0.6623 - val_loss: 3.1990
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0574 - val_accuracy: 0.7013 - val_loss: 2.6595
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0051 - val_accuracy: 0.7013 - val_loss: 2.6603
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.8803e-04 - val_accuracy: 0.7013 - val_loss: 2.7225
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.8396e-04 - val_accuracy: 0.7078 - val_loss: 2.8118
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3094e-04 - val_accuracy: 0.7143 - val_loss: 2.9224
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.0731e-05 - val_accuracy: 0.7078 - val_loss: 2.9717
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0674 - val_accuracy: 0.7273 - val_loss: 2.6760
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.2466e-04 - val_accuracy: 0.7208 - val_loss: 2.5871
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3635e-04 - val_accuracy: 0.7273 - val_loss: 2.6440
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0849e-04 - val_accuracy: 0.7273 - val_loss: 2.6937
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.9524e-05 - val_accuracy: 0.7273 - val_loss: 2.7591
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.4432e-05 - val_accuracy: 0.7273 - val_loss: 2.8960
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.8190e-05 - val_accuracy: 0.7208 - val_loss: 3.0266
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.4223e-05 - val_accuracy: 0.7403 - val_loss: 3.0715
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.0792 - val_accuracy: 0.7143 - val_loss: 3.0949
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.7013 - val_loss: 3.0423
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.3378e-05 - val_accuracy: 0.7078 - val_loss: 3.1103
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.4648e-05 - val_accuracy: 0.7078 - val_loss: 3.1518
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.1328e-05 - val_accuracy: 0.7078 - val_loss: 3.2044
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9902 - loss: 0.0367 - val_accuracy: 0.7143 - val_loss: 3.0259
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0234 - val_accuracy: 0.7208 - val_loss: 2.8162
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9902 - loss: 0.0283 - val_accuracy: 0.7403 - val_loss: 2.7581
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.2231e-04 - val_accuracy: 0.7468 - val_loss: 2.7991
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1098e-04 - val_accuracy: 0.7403 - val_loss: 2.8588
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 7.9654e-05 - val_accuracy: 0.7403 - val_loss: 2.9309
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.5952e-05 - val_accuracy: 0.7403 - val_loss: 3.0529
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.7261e-05 - val_accuracy: 0.7403 - val_loss: 3.2799
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0675 - val_accuracy: 0.7013 - val_loss: 2.9301
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0328 - val_accuracy: 0.7013 - val_loss: 2.7407
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0274 - val_accuracy: 0.7273 - val_loss: 2.7735
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.9701e-04 - val_accuracy: 0.7143 - val_loss: 2.8465
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3807e-04 - val_accuracy: 0.7078 - val_loss: 2.9158

In [94]:
def build_model(hp):
    model = Sequential()

    counter=0

    for i in range(hp.Int("num_layers", min_value=1, max_value=10)):

      if counter==0:

        model.add(
            Dense(
                # Tune number of units separately.
                units=hp.Int("units"+str(i), min_value=32, max_value=512, step=32),
                activation=hp.Choice("activation"+str(i), ["relu", "tanh","sigmoid"]),
                input_dim=8
            )
        )
      else:

          model.add(
            Dense(
                # Tune number of units separately.
                units=hp.Int("units"+str(i), min_value=32, max_value=512, step=32),
                activation=hp.Choice("activation"+str(i), ["relu", "tanh","sigmoid"])
            )
        )
    counter+=1

    model.add(Dense(1,activation="sigmoid"))
    optimizer=hp.Choice("optimizer", values=["adam","sgd","rmsprop","Adagrad"])
    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )

    return model

In [95]:
tuner2 = kt.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=5,directory="mydir2"
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [96]:
tuner2.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 17s

In [97]:
tuner2.search_space_summary()

Search space summary
Default search space size: 22
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 10, 'step': 1, 'sampling': 'linear'}
units0 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation0 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'sgd', 'rmsprop', 'Adagrad'], 'ordered': False}
units1 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation1 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units2 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation2 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units3 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation3 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units4 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation4 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units5 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation5 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units6 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation6 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units7 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation7 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units8 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation8 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}
units9 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': 'linear'}
activation9 (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'tanh', 'sigmoid'], 'ordered': False}

In [98]:
tuner2.results_summary()

Results summary
Results in mydir2/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
num_layers: 1
units0: 224
activation0: tanh
optimizer: sgd
Score: 0.8181818127632141

Trial 1 summary
Hyperparameters:
num_layers: 10
units0: 416
activation0: relu
optimizer: rmsprop
units1: 32
activation1: relu
units2: 32
activation2: relu
units3: 32
activation3: relu
units4: 32
activation4: relu
units5: 32
activation5: relu
units6: 32
activation6: relu
units7: 32
activation7: relu
units8: 32
activation8: relu
units9: 32
activation9: relu
Score: 0.8181818127632141

Trial 3 summary
Hyperparameters:
num_layers: 5
units0: 192
activation0: relu
optimizer: rmsprop
units1: 352
activation1: relu
units2: 224
activation2: tanh
units3: 320
activation3: sigmoid
units4: 192
activation4: sigmoid
units5: 512
activation5: tanh
units6: 512
activation6: relu
units7: 128
activation7: relu
units8: 480
activation8: tanh
units9: 448
activation9: relu
Score: 0.7792207598686218

Trial 2 summary
Hyperparameters:
num_layers: 4
units0: 128
activation0: tanh
optimizer: sgd
units1: 64
activation1: sigmoid
units2: 416
activation2: tanh
units3: 352
activation3: sigmoid
units4: 352
activation4: relu
units5: 64
activation5: relu
units6: 384
activation6: tanh
units7: 416
activation7: relu
units8: 160
activation8: relu
units9: 480
activation9: sigmoid
Score: 0.6428571343421936

Trial 4 summary
Hyperparameters:
num_layers: 10
units0: 512
activation0: relu
optimizer: Adagrad
units1: 320
activation1: sigmoid
units2: 224
activation2: sigmoid
units3: 160
activation3: relu
units4: 192
activation4: sigmoid
units5: 416
activation5: sigmoid
units6: 320
activation6: sigmoid
units7: 32
activation7: relu
units8: 32
activation8: relu
units9: 416
activation9: sigmoid
Score: 0.6428571343421936

In [99]:
best_hps = tuner2.get_best_hyperparameters()[0].values

In [100]:
best_hps

{'num_layers': 1, 'units0': 224, 'activation0': 'tanh', 'optimizer': 'sgd'}

In [101]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 40)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 40)             │         1,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            41 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23,764 (92.83 KB)

 Trainable params: 11,881 (46.41 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 11,883 (46.42 KB)

In [102]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 1.0000 - loss: 7.9811e-05 - val_accuracy: 0.7078 - val_loss: 2.9685
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 6.0029e-05 - val_accuracy: 0.7078 - val_loss: 3.0319
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.8044e-05 - val_accuracy: 0.7143 - val_loss: 3.1662
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0090 - val_accuracy: 0.7338 - val_loss: 3.1273
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0110 - val_accuracy: 0.7338 - val_loss: 2.8715
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.6944e-05 - val_accuracy: 0.7143 - val_loss: 2.9945
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.7483e-05 - val_accuracy: 0.7208 - val_loss: 3.0273
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.5758e-05 - val_accuracy: 0.7208 - val_loss: 3.0699
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.3503e-05 - val_accuracy: 0.7143 - val_loss: 3.1411
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.6517e-05 - val_accuracy: 0.7143 - val_loss: 3.1826
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.9158e-05 - val_accuracy: 0.7208 - val_loss: 3.2978
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0352 - val_accuracy: 0.7338 - val_loss: 3.4566
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0322 - val_accuracy: 0.7143 - val_loss: 2.9809
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9935 - loss: 0.0142 - val_accuracy: 0.7338 - val_loss: 2.9227
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0338 - val_accuracy: 0.7208 - val_loss: 3.4366
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0405 - val_accuracy: 0.7208 - val_loss: 2.9133
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.9310e-04 - val_accuracy: 0.7273 - val_loss: 2.9070
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.2663e-05 - val_accuracy: 0.7208 - val_loss: 2.9709
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.7759e-05 - val_accuracy: 0.7208 - val_loss: 3.0616
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.1031e-05 - val_accuracy: 0.7208 - val_loss: 3.1225
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.9837e-05 - val_accuracy: 0.7143 - val_loss: 3.2303
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.5792e-05 - val_accuracy: 0.7143 - val_loss: 3.4050
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.1744e-05 - val_accuracy: 0.7143 - val_loss: 3.6424
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.1088 - val_accuracy: 0.7143 - val_loss: 2.9777
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.5415e-04 - val_accuracy: 0.7143 - val_loss: 2.9730
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.0755e-05 - val_accuracy: 0.7143 - val_loss: 2.9918
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.2293e-05 - val_accuracy: 0.7078 - val_loss: 3.0199
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.3790e-05 - val_accuracy: 0.7078 - val_loss: 3.0593
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.5135e-05 - val_accuracy: 0.7013 - val_loss: 3.1483
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.8902e-05 - val_accuracy: 0.7013 - val_loss: 3.2287
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3426e-05 - val_accuracy: 0.7078 - val_loss: 3.2870
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0951e-05 - val_accuracy: 0.7078 - val_loss: 3.3713
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.1874e-06 - val_accuracy: 0.7078 - val_loss: 3.4035
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 7.4148e-06 - val_accuracy: 0.7013 - val_loss: 3.4511
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.4437e-06 - val_accuracy: 0.7078 - val_loss: 3.4885
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.7834e-06 - val_accuracy: 0.7078 - val_loss: 3.5127
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 5.2002e-06 - val_accuracy: 0.7078 - val_loss: 3.5417
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.7740e-06 - val_accuracy: 0.7078 - val_loss: 3.5622
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.3243e-06 - val_accuracy: 0.7078 - val_loss: 3.5838
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.0772e-06 - val_accuracy: 0.7078 - val_loss: 3.6075
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.7896e-06 - val_accuracy: 0.7078 - val_loss: 3.6257
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.5295e-06 - val_accuracy: 0.7078 - val_loss: 3.6465
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.3650e-06 - val_accuracy: 0.7078 - val_loss: 3.6619
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.0956e-06 - val_accuracy: 0.7078 - val_loss: 3.6757
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.0041e-06 - val_accuracy: 0.7078 - val_loss: 3.6906
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.7821e-06 - val_accuracy: 0.7078 - val_loss: 3.7066
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.6494e-06 - val_accuracy: 0.7078 - val_loss: 3.7285
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.5269e-06 - val_accuracy: 0.7078 - val_loss: 3.7395
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.4116e-06 - val_accuracy: 0.7078 - val_loss: 3.7506
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 2.3321e-06 - val_accuracy: 0.7078 - val_loss: 3.7614
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 2.2183e-06 - val_accuracy: 0.7078 - val_loss: 3.7694
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 2.1874e-06 - val_accuracy: 0.7078 - val_loss: 3.7795
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 2.0292e-06 - val_accuracy: 0.7078 - val_loss: 3.7958
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.9635e-06 - val_accuracy: 0.7078 - val_loss: 3.8052
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.8887e-06 - val_accuracy: 0.7078 - val_loss: 3.8149
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.8355e-06 - val_accuracy: 0.7078 - val_loss: 3.8271
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.7712e-06 - val_accuracy: 0.7078 - val_loss: 3.8309
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 1.7136e-06 - val_accuracy: 0.7078 - val_loss: 3.8375
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.6694e-06 - val_accuracy: 0.7078 - val_loss: 3.8500
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.6221e-06 - val_accuracy: 0.7078 - val_loss: 3.8575
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 1.5763e-06 - val_accuracy: 0.7078 - val_loss: 3.8629
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.5386e-06 - val_accuracy: 0.7078 - val_loss: 3.8684
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.5067e-06 - val_accuracy: 0.7078 - val_loss: 3.8728
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.4629e-06 - val_accuracy: 0.7078 - val_loss: 3.8710
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.4214e-06 - val_accuracy: 0.7078 - val_loss: 3.8813
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3857e-06 - val_accuracy: 0.7078 - val_loss: 3.8901
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.3572e-06 - val_accuracy: 0.7078 - val_loss: 3.8975
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.3233e-06 - val_accuracy: 0.7078 - val_loss: 3.9013
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2952e-06 - val_accuracy: 0.7078 - val_loss: 3.9064
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.2658e-06 - val_accuracy: 0.7078 - val_loss: 3.9273
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2460e-06 - val_accuracy: 0.7078 - val_loss: 3.9293
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.2243e-06 - val_accuracy: 0.7078 - val_loss: 3.9303
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1898e-06 - val_accuracy: 0.7078 - val_loss: 3.9338
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1693e-06 - val_accuracy: 0.7078 - val_loss: 3.9369
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1435e-06 - val_accuracy: 0.7078 - val_loss: 3.9430
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.1179e-06 - val_accuracy: 0.7078 - val_loss: 3.9473
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.1008e-06 - val_accuracy: 0.7078 - val_loss: 3.9525
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.0763e-06 - val_accuracy: 0.7078 - val_loss: 3.9562
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0560e-06 - val_accuracy: 0.7078 - val_loss: 3.9618
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0382e-06 - val_accuracy: 0.7078 - val_loss: 3.9639
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0217e-06 - val_accuracy: 0.7078 - val_loss: 3.9680
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0034e-06 - val_accuracy: 0.7078 - val_loss: 3.9723
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.9020e-07 - val_accuracy: 0.7078 - val_loss: 3.9826
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.6812e-07 - val_accuracy: 0.7078 - val_loss: 3.9856
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.4937e-07 - val_accuracy: 0.7078 - val_loss: 3.9888
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.3792e-07 - val_accuracy: 0.7078 - val_loss: 3.9926
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.2046e-07 - val_accuracy: 0.7078 - val_loss: 3.9935
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 9.0865e-07 - val_accuracy: 0.7078 - val_loss: 3.9979
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.9647e-07 - val_accuracy: 0.7078 - val_loss: 3.9993
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 8.7983e-07 - val_accuracy: 0.7078 - val_loss: 4.0020
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.6764e-07 - val_accuracy: 0.7078 - val_loss: 4.0069
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.5466e-07 - val_accuracy: 0.7078 - val_loss: 4.0112
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.4154e-07 - val_accuracy: 0.7078 - val_loss: 4.0168
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 8.2968e-07 - val_accuracy: 0.7078 - val_loss: 4.0204