<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/29_Keras_Tuner_Hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [75]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/DeepLearning/master/diabetes_1.csv")

In [76]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [77]:
df.corr()["Outcome"]  #to check which coloumn is useful ,we can ignore unused column

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [78]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [79]:
scale=StandardScaler()
X=scale.fit_transform(X)

In [80]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=1)

In [81]:
model=Sequential()
model.add(Dense(32,activation="relu", input_dim=8))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [82]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.compile(optimizer="adam",loss="binary_crossentropy", metrics=["accuracy"])

In [84]:
model.fit(X_train,y_train,batch_size=32,epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.4104 - loss: 0.8565 - val_accuracy: 0.4416 - val_loss: 0.7795
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4739 - loss: 0.7584 - val_accuracy: 0.5000 - val_loss: 0.6982
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5179 - loss: 0.6889 - val_accuracy: 0.6234 - val_loss: 0.6388
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6303 - loss: 0.6368 - val_accuracy: 0.7338 - val_loss: 0.5981
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5977 - val_accuracy: 0.7532 - val_loss: 0.5640
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.5675 - val_accuracy: 0.7662 - val_loss: 0.5410
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.5445 - val_accuracy: 0.7727 - val_loss: 0.5239
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.5256 - val_accuracy: 0.7727 - val_loss: 0.5094
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7818 - loss: 0.5113 - val_accuracy: 0.7532 - val_loss: 0.4988
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7818 - loss: 0.4998 - val_accuracy: 0.7532 - val_loss: 0.4916
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7818 - loss: 0.4912 - val_accuracy: 0.7468 - val_loss: 0.4846
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4848 - val_accuracy: 0.7532 - val_loss: 0.4830
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7818 - loss: 0.4798 - val_accuracy: 0.7532 - val_loss: 0.4808
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4757 - val_accuracy: 0.7532 - val_loss: 0.4770
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7801 - loss: 0.4713 - val_accuracy: 0.7597 - val_loss: 0.4748
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7818 - loss: 0.4682 - val_accuracy: 0.7662 - val_loss: 0.4732
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7850 - loss: 0.4651 - val_accuracy: 0.7662 - val_loss: 0.4725
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7818 - loss: 0.4628 - val_accuracy: 0.7662 - val_loss: 0.4711
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4605 - val_accuracy: 0.7662 - val_loss: 0.4707
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4591 - val_accuracy: 0.7597 - val_loss: 0.4699
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7866 - loss: 0.4580 - val_accuracy: 0.7597 - val_loss: 0.4691
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7899 - loss: 0.4569 - val_accuracy: 0.7727 - val_loss: 0.4700
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7899 - loss: 0.4554 - val_accuracy: 0.7727 - val_loss: 0.4702
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4541 - val_accuracy: 0.7727 - val_loss: 0.4702
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7932 - loss: 0.4530 - val_accuracy: 0.7532 - val_loss: 0.4689
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4524 - val_accuracy: 0.7597 - val_loss: 0.4669
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7883 - loss: 0.4509 - val_accuracy: 0.7597 - val_loss: 0.4670
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4502 - val_accuracy: 0.7662 - val_loss: 0.4668
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7866 - loss: 0.4489 - val_accuracy: 0.7662 - val_loss: 0.4672
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7915 - loss: 0.4487 - val_accuracy: 0.7597 - val_loss: 0.4680
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7932 - loss: 0.4475 - val_accuracy: 0.7727 - val_loss: 0.4651
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7915 - loss: 0.4468 - val_accuracy: 0.7727 - val_loss: 0.4649
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7899 - loss: 0.4465 - val_accuracy: 0.7727 - val_loss: 0.4649
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4454 - val_accuracy: 0.7727 - val_loss: 0.4642
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7915 - loss: 0.4446 - val_accuracy: 0.7792 - val_loss: 0.4625
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4445 - val_accuracy: 0.7792 - val_loss: 0.4652
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4436 - val_accuracy: 0.7792 - val_loss: 0.4635
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7899 - loss: 0.4430 - val_accuracy: 0.7792 - val_loss: 0.4634
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4423 - val_accuracy: 0.7792 - val_loss: 0.4643
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4423 - val_accuracy: 0.7792 - val_loss: 0.4649
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4410 - val_accuracy: 0.7792 - val_loss: 0.4639
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4404 - val_accuracy: 0.7857 - val_loss: 0.4631
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4402 - val_accuracy: 0.7857 - val_loss: 0.4636
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4391 - val_accuracy: 0.7857 - val_loss: 0.4633
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4390 - val_accuracy: 0.7922 - val_loss: 0.4642
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4386 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4380 - val_accuracy: 0.7857 - val_loss: 0.4653
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4373 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4374 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4365 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4357 - val_accuracy: 0.7922 - val_loss: 0.4634
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4359 - val_accuracy: 0.7857 - val_loss: 0.4661
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4352 - val_accuracy: 0.7857 - val_loss: 0.4642
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4344 - val_accuracy: 0.7922 - val_loss: 0.4645
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4342 - val_accuracy: 0.7922 - val_loss: 0.4632
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4333 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4331 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4320 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4314 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4310 - val_accuracy: 0.7922 - val_loss: 0.4624
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4308 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4296 - val_accuracy: 0.8052 - val_loss: 0.4596
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4298 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4293 - val_accuracy: 0.8052 - val_loss: 0.4591
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4289 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4282 - val_accuracy: 0.7987 - val_loss: 0.4580
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4280 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4282 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4275 - val_accuracy: 0.8117 - val_loss: 0.4592
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4578
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.8052 - val_loss: 0.4577
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4263 - val_accuracy: 0.8052 - val_loss: 0.4568
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4258 - val_accuracy: 0.8117 - val_loss: 0.4563
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4251 - val_accuracy: 0.8117 - val_loss: 0.4554
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.8117 - val_loss: 0.4557
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4249 - val_accuracy: 0.8182 - val_loss: 0.4566
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4246 - val_accuracy: 0.8117 - val_loss: 0.4571
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4237 - val_accuracy: 0.8117 - val_loss: 0.4579
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4238 - val_accuracy: 0.8117 - val_loss: 0.4573
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4566
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4235 - val_accuracy: 0.8052 - val_loss: 0.4553
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4222 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4218 - val_accuracy: 0.8117 - val_loss: 0.4566
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7964 - loss: 0.4219 - val_accuracy: 0.8117 - val_loss: 0.4558
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8013 - loss: 0.4221 - val_accuracy: 0.8247 - val_loss: 0.4577
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7980 - loss: 0.4205 - val_accuracy: 0.8182 - val_loss: 0.4544
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7932 - loss: 0.4203 - val_accuracy: 0.8117 - val_loss: 0.4543
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7948 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7948 - loss: 0.4196 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7964 - loss: 0.4190 - val_accuracy: 0.8117 - val_loss: 0.4540
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8029 - loss: 0.4193 - val_accuracy: 0.8052 - val_loss: 0.4561
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8013 - loss: 0.4183 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7948 - loss: 0.4194 - val_accuracy: 0.8052 - val_loss: 0.4550
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7948 - loss: 0.4182 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7964 - loss: 0.4173 - val_accuracy: 0.8117 - val_loss: 0.4547
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7964 - loss: 0.4169 - val_accuracy: 0.8182 - val_loss: 0.4545
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.8046 - loss: 0.4164 - val_accuracy: 0.8117 - val_loss: 0.4556
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 0.4165 - val_accuracy: 0.8182 - val_loss: 0.4543

In [85]:
#.How to select Appropriate Optimizer
#No of Nodes In a layers
# how to select no of Hidden layers
#All in one

**#.How to select Appropriate Optimizer**

In [86]:
#pip install -U keras.tuner

In [87]:
import keras_tuner as kt

In [88]:
def build_model(hp):

  model=Sequential()
  model.add(Dense(32,activation="relu", input_dim=8))
  model.add(Dense(1,activation="sigmoid"))

  optimizer=hp.Choice("optimizer", values=["adam","sgd","rmsprop","Adagrad"])

  model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
  return model

In [89]:
tuner = kt.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=5
)

Reloading Tuner from ./untitled_project/tuner0.json

In [90]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [91]:
tuner.search_space_summary()

Search space summary
Default search space size: 1
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'sgd', 'rmsprop', 'Adagrad'], 'ordered': False}

In [92]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7077922224998474

Trial 1 summary
Hyperparameters:
optimizer: adam
Score: 0.701298713684082

Trial 0 summary
Hyperparameters:
optimizer: Adagrad
Score: 0.5779221057891846

Trial 2 summary
Hyperparameters:
optimizer: sgd
Score: 0.5584415793418884

In [93]:
best_hps = tuner.get_best_hyperparameters()[0].values

In [94]:
best_hps

{'optimizer': 'rmsprop'}

In [95]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [96]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [99]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8111 - loss: 0.4060 - val_accuracy: 0.7922 - val_loss: 0.4835
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8143 - loss: 0.4058 - val_accuracy: 0.7987 - val_loss: 0.4835
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8143 - loss: 0.4054 - val_accuracy: 0.8052 - val_loss: 0.4836
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8111 - loss: 0.4057 - val_accuracy: 0.7987 - val_loss: 0.4834
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4054 - val_accuracy: 0.8052 - val_loss: 0.4822
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4049 - val_accuracy: 0.8052 - val_loss: 0.4829
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4050 - val_accuracy: 0.7987 - val_loss: 0.4802
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4047 - val_accuracy: 0.7987 - val_loss: 0.4793
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4043 - val_accuracy: 0.8052 - val_loss: 0.4793
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4041 - val_accuracy: 0.7987 - val_loss: 0.4797
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4042 - val_accuracy: 0.8052 - val_loss: 0.4802
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4040 - val_accuracy: 0.8052 - val_loss: 0.4793
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4034 - val_accuracy: 0.8052 - val_loss: 0.4809
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4039 - val_accuracy: 0.8052 - val_loss: 0.4809
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4031 - val_accuracy: 0.7987 - val_loss: 0.4808
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4033 - val_accuracy: 0.8052 - val_loss: 0.4814
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4029 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4028 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4026 - val_accuracy: 0.8052 - val_loss: 0.4824
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4020 - val_accuracy: 0.7987 - val_loss: 0.4808
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4021 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4021 - val_accuracy: 0.8052 - val_loss: 0.4823
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4014 - val_accuracy: 0.8052 - val_loss: 0.4816
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4011 - val_accuracy: 0.8052 - val_loss: 0.4816
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4010 - val_accuracy: 0.7987 - val_loss: 0.4836
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4011 - val_accuracy: 0.8052 - val_loss: 0.4832
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4007 - val_accuracy: 0.8052 - val_loss: 0.4832
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4003 - val_accuracy: 0.8052 - val_loss: 0.4823
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4002 - val_accuracy: 0.7987 - val_loss: 0.4813
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3999 - val_accuracy: 0.8052 - val_loss: 0.4814
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3998 - val_accuracy: 0.7987 - val_loss: 0.4814
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3994 - val_accuracy: 0.7987 - val_loss: 0.4808
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3993 - val_accuracy: 0.7987 - val_loss: 0.4806
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3991 - val_accuracy: 0.7987 - val_loss: 0.4806
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8143 - loss: 0.3987 - val_accuracy: 0.7987 - val_loss: 0.4813
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3990 - val_accuracy: 0.7987 - val_loss: 0.4813
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.3981 - val_accuracy: 0.8052 - val_loss: 0.4804
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3983 - val_accuracy: 0.7987 - val_loss: 0.4812
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.3981 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8241 - loss: 0.3978 - val_accuracy: 0.7987 - val_loss: 0.4821
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.3978 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3979 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8257 - loss: 0.3973 - val_accuracy: 0.8052 - val_loss: 0.4824
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.3973 - val_accuracy: 0.7987 - val_loss: 0.4826
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.3971 - val_accuracy: 0.7987 - val_loss: 0.4831
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3972 - val_accuracy: 0.7987 - val_loss: 0.4807
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3963 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3963 - val_accuracy: 0.7987 - val_loss: 0.4814
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3963 - val_accuracy: 0.7987 - val_loss: 0.4816
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3960 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3957 - val_accuracy: 0.8052 - val_loss: 0.4820
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3951 - val_accuracy: 0.7987 - val_loss: 0.4815
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3954 - val_accuracy: 0.7987 - val_loss: 0.4824
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3952 - val_accuracy: 0.7987 - val_loss: 0.4821
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3946 - val_accuracy: 0.7987 - val_loss: 0.4832
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3952 - val_accuracy: 0.7987 - val_loss: 0.4837
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3943 - val_accuracy: 0.8052 - val_loss: 0.4827
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3944 - val_accuracy: 0.8052 - val_loss: 0.4820
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3939 - val_accuracy: 0.7987 - val_loss: 0.4822
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3939 - val_accuracy: 0.7987 - val_loss: 0.4824
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3936 - val_accuracy: 0.7987 - val_loss: 0.4838
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3929 - val_accuracy: 0.7987 - val_loss: 0.4821
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3937 - val_accuracy: 0.7987 - val_loss: 0.4813
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3929 - val_accuracy: 0.7987 - val_loss: 0.4831
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3929 - val_accuracy: 0.7987 - val_loss: 0.4842
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3927 - val_accuracy: 0.7987 - val_loss: 0.4842
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3923 - val_accuracy: 0.7987 - val_loss: 0.4874
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3921 - val_accuracy: 0.7987 - val_loss: 0.4868
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3916 - val_accuracy: 0.7987 - val_loss: 0.4857
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3916 - val_accuracy: 0.7987 - val_loss: 0.4867
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3921 - val_accuracy: 0.7922 - val_loss: 0.4875
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3916 - val_accuracy: 0.7987 - val_loss: 0.4877
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3911 - val_accuracy: 0.7922 - val_loss: 0.4883
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3910 - val_accuracy: 0.7922 - val_loss: 0.4877
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3906 - val_accuracy: 0.7987 - val_loss: 0.4886
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3910 - val_accuracy: 0.7922 - val_loss: 0.4874
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3899 - val_accuracy: 0.7922 - val_loss: 0.4879
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3905 - val_accuracy: 0.7987 - val_loss: 0.4874
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3899 - val_accuracy: 0.7987 - val_loss: 0.4883
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3896 - val_accuracy: 0.7987 - val_loss: 0.4864
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3897 - val_accuracy: 0.7987 - val_loss: 0.4850
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3891 - val_accuracy: 0.7987 - val_loss: 0.4849
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3888 - val_accuracy: 0.7987 - val_loss: 0.4849
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3889 - val_accuracy: 0.7987 - val_loss: 0.4861
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3884 - val_accuracy: 0.7987 - val_loss: 0.4871
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3885 - val_accuracy: 0.7987 - val_loss: 0.4877
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3875 - val_accuracy: 0.7987 - val_loss: 0.4875
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3882 - val_accuracy: 0.7987 - val_loss: 0.4863
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3872 - val_accuracy: 0.7987 - val_loss: 0.4872
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3878 - val_accuracy: 0.7987 - val_loss: 0.4882
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3875 - val_accuracy: 0.7987 - val_loss: 0.4892
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3867 - val_accuracy: 0.7987 - val_loss: 0.4909
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3866 - val_accuracy: 0.7987 - val_loss: 0.4913
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3863 - val_accuracy: 0.7987 - val_loss: 0.4906