<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/9_backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=[['cgpa', 'profile_score', 'lpa']])

In [74]:
df.head()

  cgpa profile_score lpa
0    8             8   4
1    7             9   5
2    6            10   6
3    5            12   7

In [75]:
df=pd.DataFrame({
    "cgpa":[8,7,6,5],
    "profile_score":[8,9,10,12],
    "lpa":[4,5,6,7]

})

In [76]:
df.head()

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [77]:
np.ones((4,3))*0.1

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [78]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [79]:
np.ones((2,1))*0.1

array([[0.1],
       [0.1]])

In [80]:
np.zeros((1,1))

array([[0.]])

In [87]:
def initialize_parameters(layer_dims):
  parameters={}
  L=len(layer_dims)

  for l in range(1,L):
    parameters["W"+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters["b"+str(l)]=np.zeros((layer_dims[l],1))
  return parameters

In [88]:
parameter=initialize_parameters([2,2,1])

In [89]:
parameter

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [90]:
parameter["W1"]

array([[0.1, 0.1],
       [0.1, 0.1]])

In [91]:
parameter["b1"]

array([[0.],
       [0.]])

In [92]:
parameter["W2"]

array([[0.1],
       [0.1]])

In [93]:
len(parameter)

4

In [94]:
def linear_forward(A_prev,W,b):
  Z= np.dot(W.T,A_prev)+b
  return Z

In [95]:
def L_layer_forward(X,parameter):

  A=X
  L = len(parameters) // 2

  for l in range(1,L+1):

    A_prev=A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [96]:
X=df[["cgpa","profile_score"]].values[0].reshape(2,1)
y=df[["lpa"]].values[0][0]
parameters=initialize_parameters([2,2,1])


y_hat,A1 = L_layer_forward(X, parameters)

In [97]:
y_hat,A1

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [98]:
((y-y_hat[0][0])**2).round(2)

np.float64(13.54)

In [99]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [100]:
y_hat=y_hat[0][0]

In [104]:
update_parameters(parameters,y,y_hat,A1,X)

In [105]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [106]:
parameters

{'W1': array([[0.11385611, 0.11385611],
        [0.11385611, 0.11385611]]),
 'b1': array([[0.00173201],
        [0.00173201]]),
 'W2': array([[0.123552],
        [0.123552]]),
 'b2': array([[0.130912]])}

In [107]:
X=df[["cgpa","profile_score"]].values[1].reshape(2,1)
y=df[["lpa"]].values[1][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.00107618],
        [0.00107618]]),
 'W2': array([[0.114976],
        [0.114976]]),
 'b2': array([[0.124336]])}

In [108]:
X=df[["cgpa","profile_score"]].values[2].reshape(2,1)
y=df[["lpa"]].values[2][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameter)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.10805488, 0.11342479],
        [0.10805488, 0.11342479]]),
 'b1': array([[0.00134248],
        [0.00134248]]),
 'W2': array([[0.118176],
        [0.118176]]),
 'b2': array([[0.129536]])}

In [109]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11716571, 0.1352908 ],
        [0.11724108, 0.13547169]]),
 'b1': array([[0.00316465],
        [0.00317972]]),
 'W2': array([[0.14179856],
        [0.14297165]]),
 'b2': array([[0.15582204]])}

In [110]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [34]:
new_weight=