<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/9_backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=[['cgpa', 'profile_score', 'lpa']])

In [6]:
df.head()

  cgpa profile_score lpa
0    8             8   4
1    7             9   5
2    6            10   6
3    5            12   7

In [7]:
df=pd.DataFrame({
    "cgpa":[8,7,6,5],
    "profile_score":[8,9,10,12],
    "lpa":[4,5,6,7]

})

In [8]:
df.head()

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [28]:
np.ones((4,3))*0.1

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [13]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [15]:
np.ones((2,1))*0.1

array([[0.1],
       [0.1]])

In [16]:
np.zeros((1,1))

array([[0.]])

In [35]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)

  for l in range(1,L):
    parameters["W"+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters["b"+str(l)]=np.zeros((layer_dims[l],1))
    return parameter

In [30]:
parameter=initialize_parameters([2,2,1])

In [31]:
parameter

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [32]:
parameter["W1"]

array([[0.1, 0.1],
       [0.1, 0.1]])

In [33]:
parameter["b1"]

array([[0.],
       [0.]])

In [34]:
parameter["W2"]

array([[0.1],
       [0.1]])